# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MonsterMapper' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MonsterMappers
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'Firebase'

  target 'MonsterMapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
